//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.6
//
// <auto-generated>
//
// Generated from file `dictionary.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __dictionary_h__
#define __dictionary_h__

#include <IceUtil/PushDisableWarnings.h>
#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/ValueF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Comparable.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/GCObject.h>
#include <Ice/Value.h>
#include <Ice/Incoming.h>
#include <Ice/FactoryTableInit.h>
#include <IceUtil/ScopedArray.h>
#include <Ice/Optional.h>
#include <Ice/ExceptionHelpers.h>
#include <IceUtil/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 >= 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 6
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace DictionaryModule
{

class translator;
class translatorPrx;

}

namespace DictionaryModule
{

class NoSuchWord : public ::Ice::UserExceptionHelper<NoSuchWord, ::Ice::UserException>
{
public:

    virtual ~NoSuchWord();

    NoSuchWord(const NoSuchWord&) = default;

    NoSuchWord() = default;

    /**
     * Obtains a tuple containing all of the exception's data members.
     * @return The data members in a tuple.
     */
    std::tuple<> ice_tuple() const
    {
        return std::tie();
    }

    /**
     * Obtains the Slice type ID of this exception.
     * @return The fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();
};

/// \cond INTERNAL
static NoSuchWord _iceS_NoSuchWord_init;
/// \endcond

using words = ::std::vector<::std::string>;

using myDictionary = ::std::map<::std::string, words>;

}

namespace DictionaryModule
{

class translator : public virtual ::Ice::Object
{
public:

    using ProxyType = translatorPrx;

    /**
     * Determines whether this object supports an interface with the given Slice type ID.
     * @param id The fully-scoped Slice type ID.
     * @param current The Current object for the invocation.
     * @return True if this object supports the interface, false, otherwise.
     */
    virtual bool ice_isA(::std::string id, const ::Ice::Current& current) const override;

    /**
     * Obtains a list of the Slice type IDs representing the interfaces supported by this object.
     * @param current The Current object for the invocation.
     * @return A list of fully-scoped type IDs.
     */
    virtual ::std::vector<::std::string> ice_ids(const ::Ice::Current& current) const override;

    /**
     * Obtains a Slice type ID representing the most-derived interface supported by this object.
     * @param current The Current object for the invocation.
     * @return A fully-scoped type ID.
     */
    virtual ::std::string ice_id(const ::Ice::Current& current) const override;

    /**
     * Obtains the Slice type ID corresponding to this class.
     * @return A fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

    virtual words translate(::std::string s, const ::Ice::Current& current) = 0;
    /// \cond INTERNAL
    bool _iceD_translate(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    /// \cond INTERNAL
    virtual bool _iceDispatch(::IceInternal::Incoming&, const ::Ice::Current&) override;
    /// \endcond
};

}

namespace DictionaryModule
{

class translatorPrx : public virtual ::Ice::Proxy<translatorPrx, ::Ice::ObjectPrx>
{
public:

    words translate(const ::std::string& s, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makePromiseOutgoing<::DictionaryModule::words>(true, this, &translatorPrx::_iceI_translate, s, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto translateAsync(const ::std::string& s, const ::Ice::Context& context = ::Ice::noExplicitContext)
        -> decltype(::std::declval<P<::DictionaryModule::words>>().get_future())
    {
        return _makePromiseOutgoing<::DictionaryModule::words, P>(false, this, &translatorPrx::_iceI_translate, s, context);
    }

    ::std::function<void()>
    translateAsync(const ::std::string& s,
                   ::std::function<void(::DictionaryModule::words)> response,
                   ::std::function<void(::std::exception_ptr)> ex = nullptr,
                   ::std::function<void(bool)> sent = nullptr,
                   const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<::DictionaryModule::words>(std::move(response), std::move(ex), std::move(sent), this, &DictionaryModule::translatorPrx::_iceI_translate, s, context);
    }

    /// \cond INTERNAL
    void _iceI_translate(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::DictionaryModule::words>>&, const ::std::string&, const ::Ice::Context&);
    /// \endcond

    /**
     * Obtains the Slice type ID of this interface.
     * @return The fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

protected:

    /// \cond INTERNAL
    translatorPrx() = default;
    friend ::std::shared_ptr<translatorPrx> IceInternal::createProxy<translatorPrx>();

    virtual ::std::shared_ptr<::Ice::ObjectPrx> _newInstance() const override;
    /// \endcond
};

}

/// \cond STREAM
namespace Ice
{

}
/// \endcond

/// \cond INTERNAL
namespace DictionaryModule
{

using translatorPtr = ::std::shared_ptr<translator>;
using translatorPrxPtr = ::std::shared_ptr<translatorPrx>;

}
/// \endcond

#else // C++98 mapping

namespace IceProxy
{

namespace DictionaryModule
{

class translator;
/// \cond INTERNAL
void _readProxy(::Ice::InputStream*, ::IceInternal::ProxyHandle< translator>&);
::IceProxy::Ice::Object* upCast(translator*);
/// \endcond

}

}

namespace DictionaryModule
{

class translator;
/// \cond INTERNAL
::Ice::Object* upCast(translator*);
/// \endcond
typedef ::IceInternal::Handle< translator> translatorPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::DictionaryModule::translator> translatorPrx;
typedef translatorPrx translatorPrxPtr;
/// \cond INTERNAL
void _icePatchObjectPtr(translatorPtr&, const ::Ice::ObjectPtr&);
/// \endcond

}

namespace DictionaryModule
{

class NoSuchWord : public ::Ice::UserException
{
public:

    NoSuchWord() {}

#ifdef ICE_CPP11_COMPILER
    NoSuchWord(const NoSuchWord&) = default;
    virtual ~NoSuchWord();
#else
    virtual ~NoSuchWord() throw();
#endif

    /**
     * Obtains the Slice type ID of this exception.
     * @return The fully-scoped type ID.
     */
    virtual ::std::string ice_id() const;
    /**
     * Polymorphically clones this exception.
     * @return A shallow copy of this exception.
     */
    virtual NoSuchWord* ice_clone() const;
    /**
     * Throws this exception.
     */
    virtual void ice_throw() const;

protected:

    /// \cond STREAM
    virtual void _writeImpl(::Ice::OutputStream*) const;
    virtual void _readImpl(::Ice::InputStream*);
    /// \endcond
};

/// \cond INTERNAL
static NoSuchWord _iceS_NoSuchWord_init;
/// \endcond

typedef ::std::vector< ::std::string> words;

typedef ::std::map< ::std::string, words> myDictionary;

}

namespace DictionaryModule
{

/**
 * Base class for asynchronous callback wrapper classes used for calls to
 * IceProxy::DictionaryModule::translator::begin_translate.
 * Create a wrapper instance by calling ::DictionaryModule::newCallback_translator_translate.
 */
class Callback_translator_translate_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_translator_translate_Base> Callback_translator_translatePtr;

}

namespace IceProxy
{

namespace DictionaryModule
{

class translator : public virtual ::Ice::Proxy<translator, ::IceProxy::Ice::Object>
{
public:

    ::DictionaryModule::words translate(const ::std::string& s, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return end_translate(_iceI_begin_translate(s, context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_translate(const ::std::string& s, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_translate(s, context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_translate(const ::std::string& s, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_translate(s, ::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_translate(const ::std::string& s, const ::Ice::Context& context, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_translate(s, context, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_translate(const ::std::string& s, const ::DictionaryModule::Callback_translator_translatePtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_translate(s, ::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_translate(const ::std::string& s, const ::Ice::Context& context, const ::DictionaryModule::Callback_translator_translatePtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_translate(s, context, cb, cookie);
    }

    ::DictionaryModule::words end_translate(const ::Ice::AsyncResultPtr& result);

private:

    ::Ice::AsyncResultPtr _iceI_begin_translate(const ::std::string&, const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    /**
     * Obtains the Slice type ID corresponding to this interface.
     * @return A fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

protected:
    /// \cond INTERNAL

    virtual ::IceProxy::Ice::Object* _newInstance() const;
    /// \endcond
};

}

}

namespace DictionaryModule
{

class translator : public virtual ::Ice::Object
{
public:

    typedef translatorPrx ProxyType;
    typedef translatorPtr PointerType;

    virtual ~translator();

#ifdef ICE_CPP11_COMPILER
    translator() = default;
    translator(const translator&) = default;
    translator& operator=(const translator&) = default;
#endif

    /**
     * Determines whether this object supports an interface with the given Slice type ID.
     * @param id The fully-scoped Slice type ID.
     * @param current The Current object for the invocation.
     * @return True if this object supports the interface, false, otherwise.
     */
    virtual bool ice_isA(const ::std::string& id, const ::Ice::Current& current = ::Ice::emptyCurrent) const;

    /**
     * Obtains a list of the Slice type IDs representing the interfaces supported by this object.
     * @param current The Current object for the invocation.
     * @return A list of fully-scoped type IDs.
     */
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& current = ::Ice::emptyCurrent) const;

    /**
     * Obtains a Slice type ID representing the most-derived interface supported by this object.
     * @param current The Current object for the invocation.
     * @return A fully-scoped type ID.
     */
    virtual const ::std::string& ice_id(const ::Ice::Current& current = ::Ice::emptyCurrent) const;

    /**
     * Obtains the Slice type ID corresponding to this class.
     * @return A fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

    virtual words translate(const ::std::string& s, const ::Ice::Current& current = ::Ice::emptyCurrent) = 0;
    /// \cond INTERNAL
    bool _iceD_translate(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    /// \cond INTERNAL
    virtual bool _iceDispatch(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

protected:

    /// \cond STREAM
    virtual void _iceWriteImpl(::Ice::OutputStream*) const;
    virtual void _iceReadImpl(::Ice::InputStream*);
    /// \endcond
};

/// \cond INTERNAL
inline bool operator==(const translator& lhs, const translator& rhs)
{
    return static_cast<const ::Ice::Object&>(lhs) == static_cast<const ::Ice::Object&>(rhs);
}

inline bool operator<(const translator& lhs, const translator& rhs)
{
    return static_cast<const ::Ice::Object&>(lhs) < static_cast<const ::Ice::Object&>(rhs);
}
/// \endcond

}

/// \cond STREAM
namespace Ice
{

template<>
struct StreamableTraits< ::DictionaryModule::NoSuchWord>
{
    static const StreamHelperCategory helper = StreamHelperCategoryUserException;
};

}
/// \endcond

namespace DictionaryModule
{

/**
 * Type-safe asynchronous callback wrapper class used for calls to
 * IceProxy::DictionaryModule::translator::begin_translate.
 * Create a wrapper instance by calling ::DictionaryModule::newCallback_translator_translate.
 */
template<class T>
class CallbackNC_translator_translate : public Callback_translator_translate_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const words&);

    CallbackNC_translator_translate(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    /// \cond INTERNAL
    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        translatorPrx proxy = translatorPrx::uncheckedCast(result->getProxy());
        words ret;
        try
        {
            ret = proxy->end_translate(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)(ret);
        }
    }
    /// \endcond

private:

    Response _response;
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::DictionaryModule::translator::begin_translate.
 */
template<class T> Callback_translator_translatePtr
newCallback_translator_translate(const IceUtil::Handle<T>& instance, void (T::*cb)(const words&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_translator_translate<T>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::DictionaryModule::translator::begin_translate.
 */
template<class T> Callback_translator_translatePtr
newCallback_translator_translate(T* instance, void (T::*cb)(const words&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_translator_translate<T>(instance, cb, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class with cookie support used for calls to
 * IceProxy::DictionaryModule::translator::begin_translate.
 * Create a wrapper instance by calling ::DictionaryModule::newCallback_translator_translate.
 */
template<class T, typename CT>
class Callback_translator_translate : public Callback_translator_translate_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const words&, const CT&);

    Callback_translator_translate(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    /// \cond INTERNAL
    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        translatorPrx proxy = translatorPrx::uncheckedCast(result->getProxy());
        words ret;
        try
        {
            ret = proxy->end_translate(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(ret, CT::dynamicCast(result->getCookie()));
        }
    }
    /// \endcond

private:

    Response _response;
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::DictionaryModule::translator::begin_translate.
 */
template<class T, typename CT> Callback_translator_translatePtr
newCallback_translator_translate(const IceUtil::Handle<T>& instance, void (T::*cb)(const words&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_translator_translate<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::DictionaryModule::translator::begin_translate.
 */
template<class T, typename CT> Callback_translator_translatePtr
newCallback_translator_translate(T* instance, void (T::*cb)(const words&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_translator_translate<T, CT>(instance, cb, excb, sentcb);
}

}

#endif

#include <IceUtil/PopDisableWarnings.h>
#endif
