//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.6
//
// <auto-generated>
//
// Generated from file `dictionary.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <dictionary.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ValueFactory.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/InputStream.h>
#include <Ice/OutputStream.h>
#include <Ice/LocalException.h>
#include <IceUtil/PopDisableWarnings.h>

#if defined(_MSC_VER)
#   pragma warning(disable:4458) // declaration of ... hides class member
#elif defined(__clang__)
#   pragma clang diagnostic ignored "-Wshadow"
#elif defined(__GNUC__)
#   pragma GCC diagnostic ignored "-Wshadow"
#endif

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 >= 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 6
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace
{

const ::IceInternal::DefaultUserExceptionFactoryInit<::DictionaryModule::NoSuchWord> iceC_DictionaryModule_NoSuchWord_init("::DictionaryModule::NoSuchWord");

const ::std::string iceC_DictionaryModule_translator_ids[2] =
{
    "::DictionaryModule::translator",
    "::Ice::Object"
};
const ::std::string iceC_DictionaryModule_translator_ops[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "translate"
};
const ::std::string iceC_DictionaryModule_translator_translate_name = "translate";

}

DictionaryModule::NoSuchWord::~NoSuchWord()
{
}

const ::std::string&
DictionaryModule::NoSuchWord::ice_staticId()
{
    static const ::std::string typeId = "::DictionaryModule::NoSuchWord";
    return typeId;
}

bool
DictionaryModule::translator::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_DictionaryModule_translator_ids, iceC_DictionaryModule_translator_ids + 2, s);
}

::std::vector<::std::string>
DictionaryModule::translator::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_DictionaryModule_translator_ids[0], &iceC_DictionaryModule_translator_ids[2]);
}

::std::string
DictionaryModule::translator::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
DictionaryModule::translator::ice_staticId()
{
    static const ::std::string typeId = "::DictionaryModule::translator";
    return typeId;
}

/// \cond INTERNAL
bool
DictionaryModule::translator::_iceD_translate(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::string iceP_s;
    istr->readAll(iceP_s);
    inS.endReadParams();
    words ret = this->translate(::std::move(iceP_s), current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
DictionaryModule::translator::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_DictionaryModule_translator_ops, iceC_DictionaryModule_translator_ops + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_DictionaryModule_translator_ops)
    {
        case 0:
        {
            return _iceD_ice_id(in, current);
        }
        case 1:
        {
            return _iceD_ice_ids(in, current);
        }
        case 2:
        {
            return _iceD_ice_isA(in, current);
        }
        case 3:
        {
            return _iceD_ice_ping(in, current);
        }
        case 4:
        {
            return _iceD_translate(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond INTERNAL
void
DictionaryModule::translatorPrx::_iceI_translate(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::DictionaryModule::words>>& outAsync, const ::std::string& iceP_s, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_DictionaryModule_translator_translate_name);
    outAsync->invoke(iceC_DictionaryModule_translator_translate_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_s);
        },
        [](const ::Ice::UserException& ex)
        {
            try
            {
                ex.ice_throw();
            }
            catch(const NoSuchWord&)
            {
                throw;
            }
            catch(const ::Ice::UserException&)
            {
            }
        });
}
/// \endcond

/// \cond INTERNAL
::std::shared_ptr<::Ice::ObjectPrx>
DictionaryModule::translatorPrx::_newInstance() const
{
    return ::IceInternal::createProxy<translatorPrx>();
}
/// \endcond

const ::std::string&
DictionaryModule::translatorPrx::ice_staticId()
{
    return translator::ice_staticId();
}

#else // C++98 mapping

namespace
{

const ::std::string iceC_DictionaryModule_translator_translate_name = "translate";

}

namespace
{

const ::IceInternal::DefaultUserExceptionFactoryInit< ::DictionaryModule::NoSuchWord> iceC_DictionaryModule_NoSuchWord_init("::DictionaryModule::NoSuchWord");

}

#ifdef ICE_CPP11_COMPILER
DictionaryModule::NoSuchWord::~NoSuchWord()
{
}
#else
DictionaryModule::NoSuchWord::~NoSuchWord() throw()
{
}
#endif

::std::string
DictionaryModule::NoSuchWord::ice_id() const
{
    return "::DictionaryModule::NoSuchWord";
}

DictionaryModule::NoSuchWord*
DictionaryModule::NoSuchWord::ice_clone() const
{
    return new NoSuchWord(*this);
}

void
DictionaryModule::NoSuchWord::ice_throw() const
{
    throw *this;
}

/// \cond STREAM
void
DictionaryModule::NoSuchWord::_writeImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice("::DictionaryModule::NoSuchWord", -1, true);
    ::Ice::StreamWriter< NoSuchWord, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
DictionaryModule::NoSuchWord::_readImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    ::Ice::StreamReader< NoSuchWord, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
/// \endcond

/// \cond INTERNAL
::IceProxy::Ice::Object* ::IceProxy::DictionaryModule::upCast(translator* p) { return p; }

void
::IceProxy::DictionaryModule::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< translator>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new translator;
        v->_copyFrom(proxy);
    }
}
/// \endcond

::Ice::AsyncResultPtr
IceProxy::DictionaryModule::translator::_iceI_begin_translate(const ::std::string& iceP_s, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_DictionaryModule_translator_translate_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_DictionaryModule_translator_translate_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_DictionaryModule_translator_translate_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_s);
        result->endWriteParams();
        result->invoke(iceC_DictionaryModule_translator_translate_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

::DictionaryModule::words
IceProxy::DictionaryModule::translator::end_translate(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_DictionaryModule_translator_translate_name);
    ::DictionaryModule::words ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::DictionaryModule::NoSuchWord&)
        {
            throw;
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

/// \cond INTERNAL
::IceProxy::Ice::Object*
IceProxy::DictionaryModule::translator::_newInstance() const
{
    return new translator;
}
/// \endcond

const ::std::string&
IceProxy::DictionaryModule::translator::ice_staticId()
{
    return ::DictionaryModule::translator::ice_staticId();
}

DictionaryModule::translator::~translator()
{
}

/// \cond INTERNAL
::Ice::Object* DictionaryModule::upCast(translator* p) { return p; }

/// \endcond

namespace
{
const ::std::string iceC_DictionaryModule_translator_ids[2] =
{
    "::DictionaryModule::translator",
    "::Ice::Object"
};

}

bool
DictionaryModule::translator::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_DictionaryModule_translator_ids, iceC_DictionaryModule_translator_ids + 2, s);
}

::std::vector< ::std::string>
DictionaryModule::translator::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_DictionaryModule_translator_ids[0], &iceC_DictionaryModule_translator_ids[2]);
}

const ::std::string&
DictionaryModule::translator::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
DictionaryModule::translator::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::DictionaryModule::translator";
    return typeId;
#else
    return iceC_DictionaryModule_translator_ids[0];
#endif
}

/// \cond INTERNAL
bool
DictionaryModule::translator::_iceD_translate(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::std::string iceP_s;
    istr->read(iceP_s);
    inS.endReadParams();
    words ret = this->translate(iceP_s, current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

namespace
{
const ::std::string iceC_DictionaryModule_translator_all[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "translate"
};

}

/// \cond INTERNAL
bool
DictionaryModule::translator::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_DictionaryModule_translator_all, iceC_DictionaryModule_translator_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_DictionaryModule_translator_all)
    {
        case 0:
        {
            return _iceD_ice_id(in, current);
        }
        case 1:
        {
            return _iceD_ice_ids(in, current);
        }
        case 2:
        {
            return _iceD_ice_isA(in, current);
        }
        case 3:
        {
            return _iceD_ice_ping(in, current);
        }
        case 4:
        {
            return _iceD_translate(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond STREAM
void
DictionaryModule::translator::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    ::Ice::StreamWriter< translator, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
DictionaryModule::translator::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    ::Ice::StreamReader< translator, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
/// \endcond

/// \cond INTERNAL
void
DictionaryModule::_icePatchObjectPtr(translatorPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = translatorPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(translator::ice_staticId(), v);
    }
}
/// \endcond

namespace Ice
{
}

#endif
